geo:
  # bounds of domain
  bounds: [-1.00,1.00, -1.00,1.00]
  # center of circle
  center: [0.0,0.0]
  # radius of circle
  radius: 0.4

mesh:
  # size of mesh
  nx: [20,20]

data:
  # name of the dataset
  name: darcy
  # directory for storing the dataset
  dirt: ./dataset
  # number of parameter
  param_size: 100
  # whether to load cache
  load_cache: True
  # batch size
  batch_size: 16

model:
  # number of input channels
  input_channel: 1
  # number of output channels
  output_channel: 1
  # number of hidden channels
  width: 32
  # fourier modes
  mode1_num: 12
  # fourier modes
  mode2_num: 12
  # padding num
  padding: 9
  # layer num
  fno_layer_num: 4
  # edge input dim
  edge_input_dim: 6
  # node input dim
  node_input_dim: 1
  # node output dim
  node_output_dim: 1
  # edge hidden dim
  edge_hidden_dim: 100
  # layer num in gno
  gno_layer_num: 1

train:
  # learinng rate
  lr: 0.001
  # scheduler step size
  step_size: 100
  # scheduler dacay rate
  gamma: 0.99
  # number of training epoch
  epoch_num: 10000

ckpt:
  # name of checkpoint
  name: gino
  # directory for storing checkpoint
  dirt: ./checkpoint

output:
  # directory for storing output
  dirt: ./result

# computing device
device: cuda
# data type
dtype: float32