geo:
  # bounds of domain
  bounds: [-1.00,1.00, -1.00,1.00]
  # center of circle
  center: [0.0,0.0]
  # radius of circle
  radius: 0.4

mesh:
  # size of mesh
  nx: [20,20]

data:
  # name of the dataset
  name: darcy
  # directory for storing the dataset
  dirt: ./dataset
  # number of parameter
  param_size: 100
  # whether to load cache
  load_cache: True
  # batch size
  batch_size: 16

model:
  # number of input channels
  in_channel: 1
  # number of output channels
  out_channel: 1
  # number of hidden channels
  width: 32
  # fourier modes
  mode1: 12
  # fourier modes
  mode2: 12
  # padding num
  padding: 9
  # layer num
  layer_num: 4
  # kernel width
  ker_width: 100
  # kernel depth
  ker_depth: 1
  # edge attribute dim
  edge_attr_dim: 6
  # node attribute dim
  node_attr_dim: 1

train:
  # learinng rate
  lr: 0.001
  # scheduler step size
  step_size: 100
  # scheduler dacay rate
  gamma: 0.99
  # number of training epoch
  epoch_num: 10000

# computing device
device: cuda
# data type
dtype: float32